var misc = ["The price of Popcorn is more than 1200% higher than its production costs.",
	"People with higher incomes generally prefer their toilet paper to come over the roll, while those with lower incomes prefer it to go under.",
	"The speed of light is 299 792 458m/s, or 1 079 252 848,8 km/h.",
	"Strawberries aren't berries, but bananas are.",
	"A snail can sleep for three years.",
	'No word in the English language rhymes with "MONTH".',
	"A cat's urine glows under a black light.",
	"The number of possible ways of playing the first four moves per side in a game of chess is 318,979,564,000.",
	'Sherlock Holmes NEVER said "Elementary, my dear Watson."',
	"Money isn't made out of paper; it's made out of cotton.",
	"The 57 on Heinz ketchup bottle represents the varieties of pickle the company once had.",
	"McDonalds makes most of it's money from real estate, not by selling burgers.",
	"On average, 12 newborns will be given to the wrong parents daily.",
	"There are no clocks in Las Vegas gambling casinos.",
	"American Airlines saved $40,000 in '87 by eliminating one olive from each salad served in first class.",
	"Most lipstick contains fish scales.",
	'After publishing his famous dictionary, Noah Webster rewrote the bible, replacing all the words he considered were "naughty".',
	"Spam was first promoted as a health food.",
	"In parts of Alaska, it's illegal to feed alcohol to a moose.",
	"This fact is false.",
	"The Dead Sea is the world's saltiest body of water, followed by League of Legends.",
	"The word ‘byte' is a contraction of ‘by eight.'",
	"The dot over the letter 'i' is called a tittle.",
	"Ingrown toenails are hereditary.",
	"It took 20,000 men 22 years to build the Taj Mahal.",
	"The average cat requires 240 calories a day.",
	"On the South Pole every direction you look is north.",
	"On the North Pole every direction you look is south.",
	"Almost all the facts in this site were copy-pasted.",
	"You should check out theuselessweb.com.",
	"The Hundred Years War of the 14th and 15th centuries actually lasted 116 years.",
	"About 50 ant farms are sold an hour.",
	"Charlie Brown's father was a barber.",
	'The word "pixel" is a contraction of either "picture cell" or "picture element".',
	'The longest one-syllable word in the English language is "screeched."',
	"Of the six men who made up the Three Stooges, three of them were real brothers.",
	"My homepage is m1ksu.ml.",
	"Emus can't walk backwards.",
	"The Washington Monument is 555 feet tall.",
	"It’s possible to lead a cow upstairs, but not downstairs.",
	"Elephants are the only mammals that can’t jump.",
	"Sharks lay the biggest eggs in the world.",
	"The creator of this site is 12 years old.",
	'The first Xbox was originally going to be called "DirectX-Box."',
	"If you count everything, including overseas territories, then France claims the title by covering 12 time zones. The United States would be the runner-up with 11 and then Russia with 9.",
	"In almost every category, culturally, economically, climatically, racially, linguistically, ethnically, and religiously India is either the most diverse countries in the world, or the runner-up.",
	"With a natural decrease in population of .8% annually, between now and 2050 Ukraine is expected to lose around 30% of its people.",
	"After some rough economic times coupled with an increased birth rate, Malta experienced significant immigration. It was so significant that there are now more Maltese living abroad than within the country itself.",
	"The best selling game ever is Tetris, with almost 500 million copies sold.",
	'The game "Grand Theft Auto 5" cost 265$ dollars to develop, making it the most expensive game ever to be made.',
	"The best selling game console is the PlaySation 2, with roughly 155 million units sold.",
	'The series "Final Fantasy" was named that, because the company "Square" was going trough rough times, making a final attempt to stay on the market with "Final Fantasy."',
	"Cherophobia is the fear of fun.",
	"Human saliva has a boiling point three times that of regular water.",
	"King Henry VIII slept with a gigantic axe beside him.",
	"An eagle can kill a young deer and fly away with it.",
	"Banging your head against a wall burns 150 calories an hour. That doesn't mean you should do it, though.",
	"In the UK, it is illegal to eat mince pies on Christmas Day.",
	"A flock of crows is known as a murder.",
	"Mitochondria is the powerhouse of the cell.",
	"Pteronophobia is the fear of being tickled by feathers.",


	"This site currently only contains 62 facts."
]

var line = 1;